# Dockerfile
FROM python:3.10
WORKDIR /opt/bot
COPY  bot qmanager-0.1.6-py3-none-any.whl logger.ini /opt/bot/
RUN pip install -r requirements.txt
RUN pip install qmanager-0.1.6-py3-none-any.whl
#EXPOSE 8080 
CMD [ "python", "bot.py"]